### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by volodymyr-kushnir** [IgorChebotenko/BSA2017_Home_Task1#1]
@IgorChebotenko ага, ще один рокстар. Привіт.
Тут всьо в порядку. Хіба може проект зробиш собі, якщо є час і бажання https://github.com/volodymyr-kushnir/agenda ? Опціонально, тотальна демократія, можна і не робити.

**Comment by IgorChebotenko** [comment]
Привіт, трохи не вшарив, розширити проект якось? чи як?

2017-05-21 16:05 GMT+03:00 Volodymyr Kushnir <notifications@github.com>:

**Comment by volodymyr-kushnir** [comment]
@IgorChebotenko ну в тебе просто проектів нема в розділі [**Projects**](https://github.com/IgorChebotenko/BSA2017_Home_Task1/projects) на **GitHub**'і. Малося на увазі, якщо маєш час і бажання, то зроби один. Ну там, наприклад, якісь завдання пододавати, конвертувати їх потім в проблеми (**issues**), вирішити, закрити ті проблеми. Таке якесь, звичний _agile development_. До лекції воно не має відношення, але просто поклікати могло б бути корисно, на власний розсуд.

**Comment by IgorChebotenko** [comment]
Додав проект)))поклацав трохи, розібрався вже в тому, дякую!)

2017-05-21 18:21 GMT+03:00 Volodymyr Kushnir <notifications@github.com>:
